### ISSUE TITLE
Integration with zk-regex

### ISSUE THREAD

**Issue by SoraSuegami** [zkemail/zk-email-verify#116]
We made a new version of zk-regex and added circom circuits for common regexes to [zk-regex-circom](https://www.npmjs.com/package/@zk-email/zk-regex-circom).
We will integrate zk-email-verify with zk-regex.

TODO:
- Update twitter circom circuits.
- Update READMEs.

**Comment by SoraSuegami** [comment]
Update twitter circom circuit.
https://github.com/zkemail/zk-email-verify/commit/f6f1ffd614093a2a8bbbaee3a74f0f428f5c97a4

**Comment by Divide-By-0** [comment]
Also remove libs/regex_to_circom.

**Comment by saleel** [comment]
Closing this as it is already done. 

> Also remove libs/regex_to_circom.

https://github.com/zkemail/zk-email-verify/pull/184
