### ISSUE TITLE
RSA Add Test for 1024 bit keys with 2048 bit circuit

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#119]
Zephyr reported that we might have a padding bug when the RSA key begins with zeros. Add a test for this in the circom tests for RSA for 1024 bit keys, for websites with poorer security.

**Comment by josediego** [comment]
Can I take a look at this? :)

**Comment by Divide-By-0** [comment]
Initially, they had reported problems with 4-8 leading 0s, but we don't have that issue since there can be at most 1: https://randomoracle.wordpress.com/2019/12/04/off-by-one-the-curious-case-of-2047-bit-rsa-keys/ and in practice, dkim keygrn is forced to have a leading 1 via the RFC.
