### ISSUE TITLE
Make zkp.ts generic

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#150]
https://github.com/zkemail/zk-email-verify/blob/e709ae8ee1019f28e1d2374e677887070fcd9ada/packages/helpers/src/zkp.ts#L8

Make this an argument, not a hardcoded twitter verifier url.

**Comment by alvinlee001** [comment]
Hi @Divide-By-0, can i make this an env variable? Or do u want it to be parameter arguments for the incoming functions?

**Comment by Divide-By-0** [comment]
> Hi @Divide-By-0, can i make this an env variable? Or do u want it to be parameter arguments for the incoming functions?

Both seems good! So we make it param args and when we run main server, we set it from the env.

**Comment by alvinlee001** [comment]
Hi @Divide-By-0, I am getting this error when running zkp.test.ts:

Error: Error downloading http://localhost:3000/email.zkeyb.gz after 3 retries

May i know if i need to start a dev server? Is there docs for that?

**Comment by saleel** [comment]
This is fixed in #163
