### ISSUE TITLE
Fix simple DKIM edge cases

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#162]
If DKIM fails, try replacing all TABs in body with spaces:  "another weird case, is the email supports TABs (ascii 9) rather than spaces".  Note that this is an easy find and replace of tabs > spaces on the frontend + in the body parsing js code.

If the email verification fails, it might be due to forwarding. This can insert labels that convert the subject from "This is the subject" to "[Label] This is the subject". We have to strip the label from the beginning of the line in such cases that DKIM verification fails.

Note that ee would need to test all such 2^n permutations of edge cases (in this case n = 2 as the emails can be tabbed/not tabbed or labeled/not labeled, adding exponentially more time to verify in the case of a failure.

I think the zkp2p fixes are here:

see: https://github.com/zkp2p/zk-p2p/blob/develop/client/src/components/ProofGen/validation/hdfc.tsx#L85
and: https://github.com/zkp2p/zk-p2p/blob/develop/client/src/components/ProofGen/validation/venmo.tsx#L62

**Comment by VasuK111** [comment]
Hello, I'm interested to solve this. Can I be please assigned with the same?

**Comment by Bisht13** [comment]
> Hello, I'm interested to solve this. Can I be please assigned with the same?

Sure @VasuK111! Please go ahead, feel free to ping if you face any issues.

**Comment by star-gazer111** [comment]
Under progress here #175 [175](https://github.com/zkemail/zk-email-verify/pull/175)

**Comment by saleel** [comment]
Fixed in #189

**Comment by saleel** [comment]
Closing this as basic setup to handle such cases is done, and known issues are handled.
We can create separate issues when new problems are found.
