### ISSUE TITLE
Replace log2 with log2_ceil

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#188]
https://github.com/zkemail/zk-email-verify/blob/6d0acdde148bd19f7e268979932d874e52ba9df5/packages/circuits/helpers/extract.circom#L33C10-L33C22

We should fully remove and deprecate log2, as it is no longer used in circomlib and I think it was a bug on our side to use that instead of log2_ceil here.

**Comment by saleel** [comment]
Will fix in #185
