### ISSUE TITLE
`log2Ceil` returns `log2(a)+1` for powers of 2

### ISSUE THREAD

**Issue by 0xbok** [zkemail/zk-email-verify#198]
this is not per the documentation: https://github.com/zkemail/zk-email-verify/blob/3b9ffd9cc59c23317dc4f89b4733f0453962b583/packages/circuits/README.md#utilsfunctionscircom

https://github.com/zkemail/zk-email-verify/blob/3b9ffd9cc59c23317dc4f89b4733f0453962b583/packages/circuits/utils/functions.circom

**Comment by saleel** [comment]
Thank you @0xbok for the notice. The behaviour is actually documented in this PR https://github.com/zkemail/zk-email-verify/pull/197/files#diff-274b090767f172f30febf42cb2b24a352a93aa0cac46f10f7c774dcb91c9050aR4

But if its only a one line change, maybe its better to correct the function. Let me check.

**Comment by saleel** [comment]
Fixed in https://github.com/zkemail/zk-email-verify/pull/197/commits/99174374f1109a0511b193407037ed2acb556ff4

Thank you.
