### ISSUE TITLE
make long_div have signal-independent control flow

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#215]
This will help us with fast witness generation for the circuits. It's a fairly small improvement and change. [Code here.](https://github.com/zkemail/zk-email-verify/blob/8685d35f9137ea566e0a07f6609fde0123d15f51/packages/circuits/lib/bigint-func.circom#L169) Context:

<img width="720" alt="image" src="https://github.com/user-attachments/assets/67d5f9f0-7dd1-4897-8d1a-4ecbb9f35edd">

I think this is a fairly small optimization anyways so it should be fine to comment out the whole code block for now. As a result, this is a very low priority task. It is important to verify that commenting this section does not affect correctness.

**Comment by iYusuqe** [comment]
@Divide-By-0 Hi, I would like to try this issue as my first OSS contribution.

**Comment by iYusuqe** [comment]
@Divide-By-0 Thank you for your comment. 
I join PSE Core program and look for some issues to contribute to. I have started studying ZK recently but have some background of math.  I continue to look for issues which I can try.
