### ISSUE TITLE
Checksum fails on snarkjs fork

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#56]
On sampritipanda version for https://github.com/sampritipanda/snarkjs/commits/zkemail. The last commit in this fork takes vivek's snarkjs fork, upgrades it to the latest version of snarkjs, fixes merged conflicts randomly till it worked, rewrote the main.cjs by basically deleting and rebuilding the package I think. Because generate_witness.js was generated using a newer version of snarkjs/circom but vivek's version was a older one so it was causing some frontend issues.

It seems main branch works however, which is strange.

**Comment by Anurag-Raut** [comment]
I'm not able to run the frontend locally, I am getting these errors on yarn install-
![image](https://user-images.githubusercontent.com/102049482/234670054-9ad76a45-f867-4546-b657-caa884e58cbc.png)
