### ISSUE TITLE
Fix Twitter Circuit Tests

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-email-verify#91]
From PR #90 (https://github.com/zkemail/zk-email-verify/pulls#issuecomment-1653670956) -- the Twitter tests seem to be broken in Docker. 

Edit: They should be tested with BOTH the stable npm packages and the latest pushes to main branch here. The former is to verify that the website will still build, and the latter are to verify that changes to the core libraries have an e2e sanity test.

**Comment by Divide-By-0** [comment]
Note that this is now for the proof-of-twitter repo: https://github.com/zkemail/proof-of-twitter

**Comment by saleel** [comment]
Closing this in favour of https://github.com/zkemail/proof-of-twitter/issues/9
